module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        black: "var(--black)",
        blue: "var(--blue)",
        "blue-text": "var(--blue-text)",
        "brand-primary": "var(--brand-primary)",
        "carbon-darkest": "var(--carbon-darkest)",
        "carbon-neutral300": "var(--carbon-neutral300)",
        "colors-default": "var(--colors-default)",
        "colors-white": "var(--colors-white)",
        colorswhite: "var(--colorswhite)",
        darklabelprimary: "var(--darklabelprimary)",
        "elements-white": "var(--elements-white)",
        "light-blue": "var(--light-blue)",
        "light-dark": "var(--light-dark)",
        "light-pink": "var(--light-pink)",
        "light-purple": "var(--light-purple)",
        "light-yellow": "var(--light-yellow)",
        listbackground: "var(--listbackground)",
        magenta: "var(--magenta)",
        medium: "var(--medium)",
        pink: "var(--pink)",
        "pink-text": "var(--pink-text)",
        "primary-blue-ocean": "var(--primary-blue-ocean)",
        "primary-navy-black": "var(--primary-navy-black)",
        "primary-pure-white": "var(--primary-pure-white)",
        "secondary-dark-grey": "var(--secondary-dark-grey)",
        "secondary-half-grey": "var(--secondary-half-grey)",
        "secondary-off-grey": "var(--secondary-off-grey)",
        "secondary-soft-grey": "var(--secondary-soft-grey)",
        "secondaryred-velvet": "var(--secondaryred-velvet)",
        "systemorange-light": "var(--systemorange-light)",
        white: "var(--white)",
        yellow: "var(--yellow)",
        "yellow-text": "var(--yellow-text)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "body-body-12": "var(--body-body-12-font-family)",
        "body-body-16-m": "var(--body-body-16-m-font-family)",
        "body-body-18": "var(--body-body-18-font-family)",
        "body-body-20": "var(--body-body-20-font-family)",
        "button-button-16": "var(--button-button-16-font-family)",
        "heading-h1": "var(--heading-h1-font-family)",
        "heading-h2": "var(--heading-h2-font-family)",
        "heading-h3": "var(--heading-h3-font-family)",
        "heading-h5": "var(--heading-h5-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
  darkMode: ["class"],
};
